version: '3.8'

services:
  meter-web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.meter-web.rule=Host(`meter.local`)'
      - 'traefik.http.services.meter-web.loadbalancer.server.port=80'
