services:
  dht11-sensor:
    build: ./apps/rp
    container_name: dht11-sensor-app
    privileged: true # Required for GPIO access
    environment:
      - PYTHONUNBUFFERED=1
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_RW_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_MEASUREMENT=${INFLUXDB_MEASUREMENT}
      - MEASUREMENT_INTERVAL=${MEASUREMENT_INTERVAL:-30}
    devices:
      - '/dev/gpiomem:/dev/gpiomem' # GPIO memory access
      - '/dev/mem:/dev/mem' # Memory access
    volumes:
      - /sys:/sys:ro
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        PUBLIC_INFLUXDB_URL: ${PUBLIC_INFLUXDB_URL}
        PUBLIC_INFLUXDB_TOKEN: ${INFLUXDB_RO_TOKEN}
        PUBLIC_INFLUXDB_ORG: ${INFLUXDB_ORG}
        PUBLIC_INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
        PUBLIC_INFLUXDB_MEASUREMENT: ${INFLUXDB_MEASUREMENT}
        PUBLIC_ORIGIN: ${PUBLIC_ORIGIN}

    container_name: meter-web
    ports:
      - '8087:80'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
