services:
  dht11-sensor:
    build: ./apps/rp
    container_name: dht11-sensor-app
    privileged: true # Required for GPIO access
    devices:
      - '/dev/gpiomem:/dev/gpiomem' # GPIO memory access
      - '/dev/mem:/dev/mem' # Memory access
    volumes:
      - /sys:/sys:ro # Read-only access to system info
      # - ./apps/rp/logs:/app/logs # Optional: mount logs directory
    restart: unless-stopped
    depends_on:
      - influxdb
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   restart: unless-stopped
  #   depends_on:
  #     - influxdb

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: meter-web
    depends_on:
      - influxdb
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
