apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url:
    secureJsonData:
      token:
    jsonData:
      version: Flux
      organization: default
      defaultBucket: default
      tlsSkipVerify: true
